### ISSUE TITLE
Problema con el placeholder en MatInput

### ISSUE THREAD

**Issue by ManuelPorteiro** [OntimizeWeb/ontimize-web-ngx#1012]
En el proyecto https://github.com/implatformdev/recadexweb estamos tratando de mostrar el placeholder de un **matInput** de Angular Material.

La versión de **Angular** que estamos utilizando es la **8.2.14**, y la versión de Material es la **8.2.3**, pero la base del proyecto está creada utilizando **Ontimize**, concretamente con la versión **8.5.4**.

El problema es que el comportamiento esperado del placeholder en el input no es el correcto, por ejemplo, que el texto del placeholder se posicione encima del texto introducido por el usuario en el input. Es decir, mientras el usuario no introduzca nada en el input, el placeholder se muestra, pero si el usuario introduce algún caracter en él, el placeholder en lugar de situarse encima del texto, desaparece.

Hemos tomado como ejemplo el código que aparece en la siguiente url: https://v8.material.angular.io/components/input/overview

![image](https://user-images.githubusercontent.com/110121575/183075774-3cb26899-a406-4b3e-8cdb-43a9c2ec2fb1.png)

Este comportamiento lo hemos replicado tanto en ventanas de diálogo como en cualquier otra lugar del proyecto. Incluso hemos observado que ocurre en un componente creado de cero y en el que no se le ha añadido código alguno en la parte de TypeScript.

Al inspeccionar los elementos de la página con el navegador, podemos ver que al placeholder se le están aplicando los estilos definidos en Ontimize.

Mencionar además que algo similar nos ocurre con los **mat-error**, ya que si el campo del formulario no pasa la validación, el texto de error no se muestra. Eso sí, la línea roja que indica el fallo, sí se muestra.

![image](https://user-images.githubusercontent.com/110121575/183076002-c9391c61-4ba5-4dc9-b47a-8aee73dc8f1e.png)

Por último, el componente **button** no reacciona a '_color="primary"_', dicho de otro modo, el botón no adquiere dicho color.

![image](https://user-images.githubusercontent.com/110121575/183076179-d334c46e-e5e2-4aea-a264-e7cf9d6df8c5.png)

**Comment by patricia-martinez-imatia** [comment]
@hi @ManuelPorteiro,

1. The first problem  problem is because you dont use `mat-label` and it is a limitation as indicated in the material documentation

![image](https://user-images.githubusercontent.com/32088627/183570677-084f1b3b-3234-4721-bd1e-0d85532910b6.png)

2. This limitation is fixed by removing this injection token in `app.module.ts`

` {provide: O_MAT_ERROR_OPTIONS, useValue: { type: 'lite' } },`

3. In the master branch the primary and accent color is the same so the color that should be shown in both cases **the same**

![image](https://user-images.githubusercontent.com/32088627/183572692-3b08cb98-2f81-4749-8506-f6d4ab267f42.png)

` //Definition primary and accent palettes`
`$mat-custom-primary: ( 50 : #e1e4e7, 100 : #b3bac2, 200 : #808d99, 300 : #4d5f70, 400 : #273c52, 500 : #011a33, 600 : #01172e, 700 : #011327, 800 : #010f20, 900 : #000814, A100 : #5577ff, A200 : #224eff, A400 : #0030ee, A700 : #002ad4, contrast: ( 50 : #000000, 100 : #000000, 200 : #000000, 300 : #ffffff, 400 : #ffffff, 500 : #ffffff, 600 : #ffffff, 700 : #ffffff, 800 : #ffffff, 900 : #ffffff, A100 : #ffffff, A200 : #ffffff, A400 : #ffffff, A700 : #ffffff, ));`

`$mat-custom-accent: ( 50 : #fce7e8, 100 : #f7c2c5, 200 : #f2999e, 300 : #ec7077, 400 : #e85259, 500 : #e4333c, 600 : #e12e36, 700 : #dd272e, 800 : #d92027, 900 : #d1141a, A100 : #ffffff, A200 : #ffcfd0, A400 : #ff9c9e, A700 : #ff8285, contrast: ( 50 : #000000, 100 : #000000, 200 : #000000, 300 : #000000, 400 : #ffffff, 500 : #ffffff, 600 : #ffffff, 700 : #ffffff, 800 : #ffffff, 900 : #ffffff, A100 : #000000, A200 : #000000, A400 : #000000, A700 : #000000, ));`

**Comment by ManuelPorteiro** [comment]
Muchas gracias por tu respuesta Patricia.

En cuanto al primer punto, efectivamente se ha resuelto tal y como indicas.
El segundo, lamentablemente no. Hemos eliminado la línea de código de "_app.module.ts_", y continuamos sin ver los mensajes de error. Para salir del paso temporalmente hemos alcanzado la siguiente aproximación. Te adjunto captura del código:

![image](https://user-images.githubusercontent.com/110121575/183863778-7950c8ce-bde9-4211-a1f0-5d7f28b4a860.png)

**Comment by patricia-martinez-imatia** [comment]
hi @ManuelPorteiro 

The solution is good, another solution would be to the following if you don't use the lite theme
`<mat-error  *ngIf="conceptForm.get('code'.hasError('pattern')" text="{{ 'CONCEPT.INPUT.ERROR.PATTERN'}}"></mat-error>`

We take note of the bug in  #1013 


Is point 3 resolved?

Regards
Thanks

**Comment by ManuelPorteiro** [comment]
Sí, el punto 3 ha sido resuelto, pero no modificando la paleta de colores. Se ha "solucionado" aplicando un estilo a los botones que deseamos que resalten, es decir, a los botones, por ejemplo para guardar cambios o crear un nuevo objeto, se le ha asignado una clase, que luego en el archivo de estilo "src\assets\css\app.scss" se adapta a lo que deseamos.

![image](https://user-images.githubusercontent.com/110121575/183893389-a3826a52-78b0-4d23-a751-e6242d112845.png)

De esta forma conseguimos que los botones se vean como se muestra en la siguiente captura:

![image](https://user-images.githubusercontent.com/110121575/183893553-db2f3ee0-0ed9-4778-9fdc-68f554a2413d.png)
