### ISSUE TITLE
Input "hidden" for  Form data components

### ISSUE THREAD

**Issue by ocdelrio** [OntimizeWeb/ontimize-web-ngx#213]
It could be beneficial to implement in form data components the input/param  "hidden" to set the visibilty. For example a  "o-integer-input" that isnt important to show to the user, but have a value, thats would be necesary to have in the form.

**Comment by manu-cr** [comment]
Since 3.1.1 the `o-form` can request extra information that it's not present in the form data components, just add the extra columns you want the form to query in the `columns` attribute. The form will store this data internally. You can get this values by calling the `getFieldValue` method of the form.
